language: node_js

node_js:
    - stable
install:
    - npm install
    - npm install istanbul coveralls mocha-lcov-reporter -D
script:
    - ./node_modules/.bin/istanbul cover --report lcov ./node_modules/mocha/bin/_mocha -- -r ts-register --recursive -R spec test/*.ts
after_script:
    - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
